config:
  partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:
    fabric-dev:
      authentication: ActiveDirectoryPassword
      user: toth.istvans@ibtconsulting.hu
      password: Almafa+234
      database: Test20241012_DWH
      host: wot2kmldd4tehg3ww6lz7tbvfe-ph6rhhpdtp6ubkibw3hcsdxhse.datawarehouse.fabric.microsoft.com
      driver: ODBC Driver 18 for SQL Server
      schema: dbo
      threads: 4
      type: fabric